collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4301075
color:
  saturation: 0.40681
  brandStrength: 0.7741935
  lightness: 0.234767
  brandColors:
    - '#FDFDFD'
    - '#A6C8EE'
    - '#8E909F'
    - '#1F1E2C'
    - '#2F3C3C'
  rhythmicContrast: 0.6863799
layout_spectrum: 1
name: HMG
